services:
  postgres:
    image: postgres:16-alpine
    container_name: sipadi-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sipadi
      POSTGRES_USER: sipadi
      POSTGRES_PASSWORD: sipadi123
    volumes:
      - sipadi-postgres-data:/var/lib/postgresql/data

volumes:
  sipadi-postgres-data:
